#!/usr/bin/env bash

if [ ! -f "$1" ]; then
	echo -e "The file's text encoding will be changed to utf-8 from euc-kr.\n[1;34mUsage:[1;31m\n$0 [file][0;0m"
	exit
fi

STRINGS=`iconv "$1" -f=UHC -t=UTF-8 -o "$1.UTF-8"`
case $? in
	0)
		mv "$1" "$1.bak"
		mv "$1.UTF-8" "$1"
		echo "[1;34m$1 [1;32mconvert succeeded[0;0m"
		;;
	1)
		rm "$1.UTF-8"
		echo "[1;34m$1 [1;31mis not korean[0;0m"
		;;
esac
