#!/usr/bin/env bash

if [ ! -d "$1" ]; then
	echo -e "[1;34mUsage:[1;31m\n$0 [dir] {file or \"*.cpp\"}[0;0m"
	exit
fi

if [ -z $2 ];
then
	find "$1" -type f -exec kr2u8 "{}" \;
else
	find "$1" -name "$2" -type f -exec kr2u8 "{}" \;
fi
